### ISSUE TITLE
addElementsToCollection() here?

### ISSUE THREAD

**Issue by boczkas** [JaroslawSlaby/ListAPITests#11]
https://github.com/JaroslawSlaby/ListAPITests/blob/6f6ff14745ea12b1e96b2473d9d6694a6d6e763c/src/test/java/tests/ListTest.java#L283

You have really nice function to add elements to collection. Is it possible to use it here also?

**Comment by boczkas** [comment]
Same in line 310

**Comment by JaroslawZaczyk** [comment]
sure. I'll correct it asap.
