### ISSUE TITLE
Name of test could be more descreptive

### ISSUE THREAD

**Issue by boczkas** [JaroslawSlaby/ListAPITests#12]
https://github.com/JaroslawSlaby/ListAPITests/blob/6f6ff14745ea12b1e96b2473d9d6694a6d6e763c/src/test/java/tests/ListTest.java#L390

equalsNonEmptyCollectionIsEqualToAnotherEmptyCollectionWithTheSameElement

**Comment by JaroslawZaczyk** [comment]
Great idea. Test looks better with your name. Thanks for info!
