### ISSUE TITLE
assertion error message 

### ISSUE THREAD

**Issue by boczkas** [JaroslawSlaby/ListAPITests#14]
https://github.com/JaroslawSlaby/ListAPITests/blob/6f6ff14745ea12b1e96b2473d9d6694a6d6e763c/src/test/java/tests/ListTest.java#L666

Assertion error message is talking about different thing that is checked in assert condition.
You're checking if elements are equal.

**Comment by JaroslawZaczyk** [comment]
o f..k. what's that? Are you sure that I've committed this?

**Comment by JaroslawZaczyk** [comment]
Fixed.
