### ISSUE TITLE
Rozwiązanie wywołania

### ISSUE THREAD

**Issue by AdrianHarenczyk** [JaroslawSlaby/ListAPITests#15]
https://github.com/JaroslawSlaby/ListAPITests/blob/6f6ff14745ea12b1e96b2473d9d6694a6d6e763c/src/test/java/tests/ListTest.java#L13

Ładne rozwiązanie wywoływania testów dla dwóch implementacji tego samego interfejsu.

**Comment by JaroslawZaczyk** [comment]
Dzięki! :D
