### ISSUE TITLE
getOperator() can be used

### ISSUE THREAD

**Issue by boczkas** [JaroslawSlaby/ListAPITests#16]
https://github.com/JaroslawSlaby/ListAPITests/blob/6f6ff14745ea12b1e96b2473d9d6694a6d6e763c/src/test/java/tests/ListTest.java#L793

"TEST_TEXT" is a magic text in here
You have really nice function getOperator() which is used 2 lines before. If I am not wrong you can use it here also

**Comment by JaroslawZaczyk** [comment]
If I do this in your way, assertion will fail. It's caused by getOperator returns lambda expression, not String. I'll create another method to replace this magic text, I promise.
